In [1]:
import pandas as pd

In [16]:
data = [1,2,3,4,5]
print(type(data))
data.mean()

<class 'list'>


AttributeError: 'list' object has no attribute 'mean'

In [9]:
import numpy as np

In [17]:
arr = np.array((1,2,3,4,5))
type(arr)

numpy.ndarray

In [18]:
arr.mean()

3.0

In [20]:
array1 = np.array([1,2,3,4,5])
array1.dtype

dtype('int64')

In [21]:
array1 = np.array([1.1,2.1,3.1,4,5])
array1.dtype

dtype('float64')

## 2차원행렬

In [22]:
matrix = np.array([[1,2],[2,3],[20,30]])
matrix

array([[ 1,  2],
       [ 2,  3],
       [20, 30]])

In [25]:
matrix2 = np.array([[3,4],[3,4],[3,4]])
matrix2

array([[3, 4],
       [3, 4],
       [3, 4]])

In [29]:
print(matrix+matrix2)
print('='*10)
print(matrix-matrix2)
print('='*10)
print(matrix*matrix2) # 행렬곱이 아닌 원소간 곱

[[ 4  6]
 [ 5  7]
 [23 34]]
[[-2 -2]
 [-1 -1]
 [17 26]]
[[  3   8]
 [  6  12]
 [ 60 120]]


In [30]:
matrix.shape

(3, 2)

In [35]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr2 = np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])

In [38]:
arr3 = np.random.randn(10)
arr3

array([ 1.40604318,  0.54285523,  0.17186819, -0.49864252,  1.72988732,
        1.40250564, -0.02606733, -0.58460428, -2.63732776, -0.24348385])

In [39]:
arr4 = np.random.randn(10,5)
arr4

array([[-0.27525985, -1.07393938, -1.6313518 , -0.90539343,  1.58009052],
       [ 0.25249439,  2.06415406, -0.23829177, -1.30533051, -2.43164194],
       [-1.16036697, -0.20015224,  0.54887191, -0.68252434, -0.48448161],
       [-0.12875407,  2.49214951, -2.2466662 , -0.23085394, -0.83780308],
       [ 1.1829115 ,  0.12509282, -0.47531769, -0.23012681, -2.29515611],
       [-0.1744219 , -0.54887443, -0.52138061, -0.01028072,  0.22701929],
       [-0.88472492, -1.98339393, -0.47049797, -0.08006911,  1.59671798],
       [ 0.29512717,  0.45234625, -0.63539625, -1.14004147, -0.82715159],
       [-0.22583251, -0.11018045,  0.55455412,  0.82883606,  0.38557312],
       [-0.32031363, -0.9180012 ,  0.6824702 , -1.11934713, -0.87058547]])

In [44]:
# 타입 변환
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(arr)
arr_float = arr.astype(np.float)
print(arr_float.dtype)
print(arr_float) # 소수점이 생김

int64
[1 2 3 4 5]
float64
[1. 2. 3. 4. 5.]


In [62]:
arr_1 = np.array([[1,2,5],[4,5,9],[6,7,34]])
print(arr_1)

print(arr_1[0,0])
print(arr_1[2,1])
print(arr_1[0,:])

[[ 1  2  5]
 [ 4  5  9]
 [ 6  7 34]]
1
7
[1 2 5]


In [67]:
arr_1[:2,:]

array([[1, 2, 5],
       [4, 5, 9]])

In [69]:
arr_1[:,1:]

array([[ 2,  5],
       [ 5,  9],
       [ 7, 34]])

In [79]:
arr2 = np.arange(1,11).reshape(5,2)
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [81]:
arr2[:1,:] = 200
arr2

array([[200, 200],
       [  3,   4],
       [  5,   6],
       [  7,   8],
       [  9,  10]])

In [96]:
print(arr2.sum())
print(arr2.sum(axis=1))
print(arr2.sum(axis=0))

452
[400   7  11  15  19]
[224 228]


In [108]:
arr3 = np.ones((3,4))
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [107]:
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])