<a href="https://colab.research.google.com/github/seungbinahn/START_AI/blob/master/02_Machine_Learning%E2%80%8E/01_numpy_%EB%A6%AC%EB%B7%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

In [ ]:
import numpy as np

## ndarray


In [ ]:
data_ndarray = np.array([10,20,30])

print(data_ndarray)
print(type(data_ndarray))

[10 20 30]
<class 'numpy.ndarray'>


In [ ]:
# ndarray 정보 출력 함수
def printinfo(array):
  print('shape = %s, dimension: %s, dtype: %s' % (array.shape, array.ndim, array.dtype))
printinfo(data_ndarray)  

shape = (3,), dimension: 1, dtype: int64


In [ ]:
array = np.array([1,2,3,4,5])
printinfo(array)

shape = (5,), dimension: 1, dtype: int64


In [ ]:
array = np.array([[1,2,3],[4,5,6]], dtype=float)
printinfo(array)

shape = (2, 3), dimension: 2, dtype: float64


In [ ]:
array = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]], dtype=float)
printinfo(array)

shape = (2, 2, 3), dimension: 3, dtype: float64


In [ ]:
# 0으로 채워진 ndarray 생성
array = np.zeros((3,4))
print(array)
printinfo(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape = (3, 4), dimension: 2, dtype: float64


In [ ]:
# 원하는 값 채우기
array = np.full((3,4),1234)
print(array)
printinfo(array)

[[1234 1234 1234 1234]
 [1234 1234 1234 1234]
 [1234 1234 1234 1234]]
shape = (3, 4), dimension: 2, dtype: int64


In [ ]:
# 초기화 없이 생성
array = np.empty((4,2))
print(array)

[[1.14193511e-316 8.48798317e-313]
 [2.46151512e-312 2.41907520e-312]
 [2.07955588e-312 2.14321575e-312]
 [5.35726157e+199 1.64338794e-312]]


In [ ]:
# 단위 정사각 행렬 생성 (identity matrix 생성)
array = np.eye(4)
print(array)
printinfo(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape = (4, 4), dimension: 2, dtype: float64


In [ ]:
# ndarray를 이용하여 같은 shape로 생성
array = np.array([[1,2,3],[4,5,6]])
print(array)

one_array = np.ones_like(array)
print(one_array)

one_array = np.zeros_like(array)
print(one_array)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [ ]:
# 랜덤값을 가지는 ndarray 생성
array = np.random.randint(0,100,20)
print(array)
print((type(array)))
array.shape

[57 74 48 84  0 59 58 57 32 46 60 14  7 60 88 44 54 20 46 37]
<class 'numpy.ndarray'>


(20,)

## ndaaray의 속성

In [ ]:
len(array)

20

In [ ]:
array.ndim

1

In [ ]:
# 배열의 모든 원소의 개수
array.size

20

In [ ]:
arr = np.arange(1,5)
print(arr.dtype)
print(arr)

arr = np.random.random((3,4))
print(arr.dtype)
print(arr)

int64
[1 2 3 4]
float64
[[0.03061383 0.92446656 0.896679   0.49415559]
 [0.49972071 0.91180601 0.86441192 0.18524392]
 [0.94994246 0.49864834 0.3173126  0.70530024]]


In [ ]:
arrlist = [[1,2,3],[4,5,6]]
nparr = np.array(arrlist, dtype=np.float)
print(nparr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# ndarray의 타입 변환
array = np.random.random((3,4))
print(array)
print(array.astype(np.int))

[[0.59987529 0.91667181 0.51865544 0.29527799]
 [0.80262971 0.43653657 0.71907732 0.59034595]
 [0.76584142 0.68847749 0.44972417 0.04889821]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# ndarray의 모양
array = np.arange(24)
print(array)
print(array.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [ ]:
# ndarray의 차원 변형 1
array.shape = (6,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# ndarray의 차원 변형 2
array.shape = (3,2,4)
print(array)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# ndarray의 차원 변형 3
array.shape = (12,2)
print(array)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [ ]:
# 원본 데이터를 유지한 채 차원을 변경한 ndarray 리턴
reshape_array = np.reshape(array, (4,6))
print(reshape_array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


## 연산

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)

b = np.arange(9,0,-1).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
# a + b, np.add(a,b)
print(a+b)
print(np.add(a,b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
# a-b np.subtract
print(a-b)
print(np.subtract(a,b))

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [ ]:
print(a)
print(b)

print(a>b)
print(a<b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[[ True  True  True]
 [ True False False]
 [False False False]]


In [ ]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)

a == b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
# 제곱근 연산
a = np.arange(1,10).reshape(3,3)
print(a)
print(np.sqrt(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
print(a)
print(np.exp(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


## 집계 함수
* 축에 따라 결과가 달리짐
* 축(axis)

In [ ]:
array = np.arange(1,10).reshape(3,3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# axis = None(dfault)

print(array.sum()) # 합
print(array.mean()) # 평균
print(array.max()) # 최대값
print(array.min()) # 최소값
print(np.median(array)) # 중앙값

45
5.0
9
1
5.0


In [ ]:
# axis = 0 각 열에 대해 계산
print(array.sum(axis=0)) # 합
print(array.mean(axis=0)) # 평균
print(array.max(axis=0)) # 최대값
print(array.min(axis=0)) # 최소값
print(np.median(array, axis=0)) # 중앙값

[12 15 18]
[4. 5. 6.]
[7 8 9]
[1 2 3]
[4. 5. 6.]


In [ ]:
# axis = 1 각 행에 대해 계산
print(array.sum(axis=1)) # 합
print(array.mean(axis=1)) # 평균
print(array.max(axis=1)) # 최대값
print(array.min(axis=1)) # 최소값
print(np.median(array, axis=1)) # 중앙값

[ 6 15 24]
[2. 5. 8.]
[3 6 9]
[1 4 7]
[2. 5. 8.]


## 인덱싱

In [ ]:
array = np.arange(16)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
array = np.arange(16).reshape((4,4))
print(array)
print(array[2,3])

array[2,3] = 777
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
11
[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10 777]
 [ 12  13  14  15]]


In [ ]:
array = np.arange(16).reshape((2,2,4))
print(array)

print(array[1,1,2])

array[1,1,2] = 777
print(array)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
14
[[[  0   1   2   3]
  [  4   5   6   7]]

 [[  8   9  10  11]
  [ 12  13 777  15]]]


In [ ]:
array = np.arange(1,11)
print(array)

print(array[2:5]) # 2에서 4 까지
print(array[:5]) # 4까지
print(array[7:]) # 7 뒤로 전체
print(array[2:-1]) # 2 에서 마지막 하나 앞까지
print(array[:]) # 전체 리스트
array[2:5] = 77
print(array)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]
[1 2 3 4 5]
[ 8  9 10]
[3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2 77 77 77  6  7  8  9 10]


In [ ]:
array = np.arange(1,17).reshape(4,4)
array[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [ ]:
array[0,2:]

array([3, 4])

In [ ]:
array[:,2]

array([ 3,  7, 11, 15])

## 데이터 생성

In [ ]:
np.linspace(0,10,5)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
array = np.arange(1,5,0.1)
array

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [ ]:
array = np.random.rand(3,4)
print(array)

[[0.79173697 0.26793577 0.94520921 0.73104216]
 [0.8795981  0.66910293 0.06786602 0.35097537]
 [0.53151408 0.25363828 0.54910335 0.31267417]]


In [ ]:
# 표준편차 1, 평균 0에 가까운 정규분포를 갖는 랜덤 값 생성
array = np.random.randn(1000)
print(array.mean())

-0.019033330635077093


In [ ]:
# np.random.randint(low,high,shape)
array = np.random.randint(0,2,10)
print(array)

array = np.random.randint(1,5,(4,4))
print(array)

[0 0 1 1 1 1 1 1 1 1]
[[2 3 1 4]
 [1 1 3 2]
 [3 2 3 3]
 [3 4 1 1]]
