<a href="https://colab.research.google.com/github/seungbinahn/START_AI/blob/master/02_Machine_Learning%E2%80%8E/03_1_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B0%9C%EC%9A%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 인공지능 개요
* Narrow AI : 좁은 영역에서 특정 task만 가능 - 정확도는 인간을 넘어섬
* General Ai : 하나의 task에서 습득한 지식을 여러 task에 적용 가능
* Super Ai : 인간을 뛰어넘은 성능을 보여주는 인공지능

## 머신러닝
* 수많은 데이터로부터 기계가 학습

# Iris(붓꽃) 분석

## Iris의 특징
* Petal(꽃잎)의 길이,넓이
* Sepal(꽃받침)의 길이, 넓이

## 임포트

In [1]:
# 사이킷런 추가
import sklearn
import pandas as pd

print(sklearn.__version__)

0.22.2.post1


In [2]:
# iris 데이터 임포트
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
iris_data = iris.data
iris_label = iris.target
print('iris target name:\n', iris.target_names)

iris target name:
 ['setosa' 'versicolor' 'virginica']


In [4]:
# iris 데이터
iris_data = iris_data
print(type(iris_data))
print(iris_data.shape)
print(iris_data[0:5]) 

<class 'numpy.ndarray'>
(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [5]:
# iris label
iris_label = iris.target
print(type(iris_label))
print(iris_label.shape)
print(iris_label[0:5]) 

<class 'numpy.ndarray'>
(150,)
[0 0 0 0 0]


## pandas로 변환

In [6]:
# iris 데이터를 pd로 변환
# data에 iris_data 등록, 칼럼명에 feature_names 등록, index는 range
df_iris = pd.DataFrame(data=iris_data, columns=iris.feature_names) 
df_iris['label'] = iris.target # label에 분류 등록
print(df_iris.shape)
df_iris.head()

(150, 5)


sepal length (cm)  sepal width (cm)  ...  petal width (cm)  label
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0
3                4.6               3.1  ...               0.2      0
4                5.0               3.6  ...               0.2      0

[5 rows x 5 columns]

In [7]:
# 분포가 정렬되어 있음
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## train, test 셋 분할

In [8]:
from sklearn.model_selection import train_test_split

# x : feature, y : label
# train : 학습용
# test : 검증용
# 전체 데이터에서 20퍼센트는 테스트셋, 80퍼센트는 학습셋으로 분할
x_train, x_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11)

In [9]:
print(iris_data.shape)
print(x_train.shape)
print(y_train.shape)

print(iris_label.shape)
print(x_test.shape)
print(y_test.shape)

(150, 4)
(120, 4)
(120,)
(150,)
(30, 4)
(30,)


## 결정트리 생성

In [10]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state = 11)

In [11]:
dt_clf.fit(X=x_train, y=y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=11, splitter='best')

## 예측
* 생성 된 모델로 테스트 셋으로 예측

In [12]:
pred = dt_clf.predict(X=x_test)

In [13]:
print(pred)
print(y_test)

[2 2 1 1 2 0 1 0 0 1 1 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1]
[2 2 2 1 2 0 1 0 0 1 2 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1]


In [14]:
pred == y_test

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [15]:
rst = (pred != y_test).sum()
rst

2

## 검증
* 결과에 대한 일치 비율

In [16]:
from sklearn.metrics import accuracy_score
print('predict accuracy : %f' % accuracy_score(y_test,pred))

predict accuracy : 0.933333
