<a href="https://colab.research.google.com/github/seungbinahn/START_AI/blob/master/02_Machine_Learning%E2%80%8E/04_1_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%84%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 전처리
* ML 알고리즘은 데이터에 기반함
* 데이터의 품질이 성능을 좌우 함
* 데이터 전처리 과정은 알고리즘 만큼 중요함
* 주요 데이터 전처리 과정 
*결손값(NaN, NULL 처리), 데이터 인코딩(Encoding), Scaling 등

### Label Encoding
* 회귀분석은 숫자의 대소관계가 결과에 영향을 미칠 수 있음
* 레이블 인코딩을 수행하면 숫자로 인식하여 모델 성능에 영향을 미칠 수 있으므로 회귀 분석에서는 사용 지양
* 트리 계열 알고리즘은 숫자의 특성이 영향이 없으므로 고민 없이 사용 가능

In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder() # LabelEncoder 생성
encoder.fit(items) # 규칙 생성

labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [2]:
print('Encoding classes : ', encoder.classes_)
print('Decoding values : ', encoder.inverse_transform([0, 1, 2, 3, 4, 5])) # decoding : 숫자를 다시 문자로 디코딩

Encoding classes :  ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
Decoding values :  ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


### One Hot Encoding
* 카테고리 값의 개수를 원소 개수로 하는 배열로 변환
* 카테고리 값에 해당하는 위치는 1, 나머지는 0으로 설정 (One Hot Vector)

In [3]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder() # 먼저 LabelEncoding 수행
encoder.fit(items)
labels = encoder.transform(items)
# reshape 행렬 크기 변환
labels = labels.reshape(-1,1) # -1 : 가변 인자, 이 경우 열은 1개로 고정, 행은 상황에 맞게 변환
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]])

In [4]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder()
one_hot_encoder.fit(labels) # n행 1열의 ndarray를 입력으로 받아 수행
one_hot_labels = one_hot_encoder.transform(labels) # 변환
print(labels)
print(type(one_hot_labels.toarray()))
print(one_hot_labels.toarray())

[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]
<class 'numpy.ndarray'>
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


### Standard Scaling
* 데이터 값의 범위를 일정 수준으로 변환하는 전처리 기법
* 표준화(Standardization) : 평균이 0, 분산이 1
* 정규화(Normalization) : 서로 다른 스케일의 데이터의 크기를 통일 ex) 0 ~ 1로 통일
* MinMaxScaler : Normalization을 손쉽게 구현

In [5]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
# df 생성
df_iris = pd.DataFrame(data = iris.data, columns = iris.feature_names)

# 원본 데이터의 통계량 확인
print("Average:\n", df_iris.mean()) # 평균 default axis = 0이므로 칼럼별로 수행
print("\nVariance:\n", df_iris.var()) # 분산 default axis = 0이므로 칼럼별로 수행

Average:
 sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

Variance:
 sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler() # Scaler 생성
scaler.fit(df_iris)
scaled_iris = scaler.transform(df_iris)

df_scaled_iris = pd.DataFrame(data=scaled_iris, columns = iris.feature_names)

# 표준화된 데이터 출력
print("Average:\n", df_scaled_iris.mean()) # 평균 default axis = 0이므로 칼럼별로 수행
print("\nVariance:\n", df_scaled_iris.var()) # 분산 default axis = 0이므로 칼럼별로 수행

Average:
 sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

Variance:
 sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMax Scaling

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(df_iris)
scaled_iris = scaler.transform(df_iris)

df_scaled_iris = pd.DataFrame(data=scaled_iris, columns = iris.feature_names)

# 정규화된 데이터 출력
print("Min value:\n", df_scaled_iris.min()) # 최소값 default axis = 0이므로 칼럼별로 수행
print("\nMax value :\n", df_scaled_iris.max()) # 최대값 default axis = 0이므로 칼럼별로 수행

Min value:
 sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

Max value :
 sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
